2801 preproc cmd
MassterMax/code_search pull request #3
Opened 2022-02-24 13:06 UTC by Ksenia-C

Add elasticsearch cluster, requires additional setup while deploying (set passwords in several places)

Update code_index with code_analyzer

2022-02-26 10:40 UTC, MassterMax requested changes

2022-02-26 10:40 UTC, MassterMax commented on codesearch/es/client.py
> +            ['localhost', 'es01'],
Что за магическое es01?

2022-02-26 10:40 UTC, MassterMax commented on codesearch/es/index_schemas/code_index.json
> +                  "(\\p{Ll}+|\\p{Lu}\\p{Ll}+|\\p{Lu}+)",
А что это делает (ради интереса)?

2022-02-26 10:40 UTC, MassterMax commented on setup.py
> +        'elasticsearch==7.16.3',
Напомни, почему тут условие строгое?

2022-02-26 12:08 UTC, Ksenia-C commented on codesearch/es/client.py
> +            ['localhost', 'es01'],
Название сервиса elasticsearch. Согласна, что надо вынести в переменные окружения. Вообще это надо, чтобы можно было обратиться к https://es01:9200

2022-02-26 12:08 UTC, Ksenia-C commented on codesearch/es/index_schemas/code_index.json
> +                  "(\\p{Ll}+|\\p{Lu}\\p{Ll}+|\\p{Lu}+)",
Здесь есть описание разных фильтров https://docs.gitlab.com/ee/development/elasticsearch.html

Именно этот - разбивает  CamelCased и lowedCameCased на токены

2022-02-26 12:08 UTC, Ksenia-C commented on setup.py
> +        'elasticsearch==7.16.3',
Иначе устанавливается 8.0.0 версия elasticsearch, а у нас запросы в формате 7.16.3. 8.0.0 еще обрабатывает 7.16.3, но чтобы перейти полностью на новую версию нужно поменять запросы. Этого мы еще не сделали

2022-03-01 14:19 UTC, MassterMax commented on setup.py
> +        'elasticsearch==7.16.3',
Добавь ограничение на версию до 8.0.0 - это можно сделать через рендж
И подмерджим)

2022-03-03 13:03 UTC, merged